### ISSUE TITLE
Missing from Package Control

### ISSUE THREAD

**Issue by saifelse** [univerio/SublimeLinter-contrib-coffee-jshint#1]
When I search for this package on Sublime 3, I don't find a result.
See: https://packagecontrol.io/search/SublimeLinter-contrib-coffee-jshint

**Comment by univerio** [comment]
Thanks for the suggestion! It's pending review: SublimeLinter/SublimeLinter3#343.

**Comment by univerio** [comment]
It's published. https://packagecontrol.io/packages/SublimeLinter-contrib-coffee-jshint
